name: PerchDisplayEntities
main: ${groupId}.${project.name}
version: "1.0.0"
author: [ emanon,KayaLambrex ]
api-version: 1.19
folia-supported: true
softdepend: [ Vault,SuperVanish,PremiumVanish,PlaceHolderAPI,GriefPrevention ]

libraries:
  - net.kyori:adventure-api:4.16.0
  - net.kyori:adventure-platform-bukkit:4.3.2
  - net.kyori:adventure-text-minimessage:4.16.0
  - net.kyori:adventure-text-serializer-gson:4.16.0
  - net.kyori:adventure-text-serializer-legacy:4.16.0

commands:
  DisplayEntities:
    description: allows to edit item in hand
    usage: /DisplayEntities
    aliases: [ de ]
  DisplayEntitiesinfo:
    description: display info of DisplayEntities
    usage: /DisplayEntitiesinfo
  DisplayEntitiesreload:
    description: reload configurations
    usage: /DisplayEntitiesreload
permissions:
  DisplayEntities.admin:
    default: op
    description: Gives full access to the plugin
    children:
      DisplayEntities.DisplayEntitiesreload: true
      DisplayEntities.DisplayEntitiesinfo: true
      DisplayEntities.bypass.*: true
  DisplayEntities.creativeuser:
    default: op
    description: Gives full access to the plugin
    children:
      DisplayEntities.*: true
  DisplayEntities.*:
    default: op
    description: Gives full access to the plugin
    children:
      DisplayEntities.create: true
      DisplayEntities.delete: true
      DisplayEntities.deselect: true
      DisplayEntities.editor: true
      DisplayEntities.select: true
      DisplayEntities.settext: true
  DisplayEntities.create:
    default: op
    description: Create new display editors
  DisplayEntities.delete:
    default: op
    description: Delect current selected display
  DisplayEntities.select:
    default: op
    description: Select nearest display
  DisplayEntities.deselect:
    default: op
    description: Deselect current selected display
  DisplayEntities.editor:
    default: op
    description: Open the editor mode
  DisplayEntities.settext:
    default: op
    description: Ability to change text of selected display text
  DisplayEntities.DisplayEntitiesinfo:
    default: op
    description: Gives full access to command /DisplayEntitiesinfo
  DisplayEntities.DisplayEntitiesreload:
    default: op
    description: Gives full access to command /DisplayEntitiesreload