# ItemEdit by Emanon
# Wiki
# Discord https://discord.gg/w5HVCDPtRp
# Donations https://www.paypal.me/FlavioLiponi/
# Spigot
#
# Do not change config-version
config-version: 1
language:
  #Default locale
  #If you want to add more languages copy language/en.yml, rename it and apply your changes,
  # plugin will automatically use it after a plugin reload or server restart
  default: 'en'
  #When true the plugin will use the client language if a language file exist for that client
  use_multilanguage: true